baseURL: https://mos9527.github.io/
title: mos9527
defaultContentLanguage: cn
theme: PaperMod
enableGitInfo: true 
languages:
  en:
    languageName: English
    weight: 10
  cn:
    languageName: 简体中文
    weight: 20
markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
          - - $
            - $
        enable: true
  tableOfContents:
    endLevel: 39
    ordered: false
    startLevel: 2          
params:
  math: true      
giscus:
    repo: "mos9527/mos9527.github.io"
    repoID: "R_kgDOLvNT9A"
    category: "Q&A"
    categoryID: "DIC_kwDOLvNT9M4CkzqN"
    mapping: "url"
    inputPosition: "top"      
params:
  env: production
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  homeInfoParams:
      Title: "My Favorite Things<blink>_</blink>"
      Translator:
        en: "Special thanks to [**@Rypie109**](https://github.com/Rypie109) for bringing English translations for these posts!"
        cn: "简体中文"

  socialIcons:
    - name: Codeforces
      url: "https://codeforces.com/profile/mos9527"
    - name: Github
      url: "https://github.com/mos9527"
    - name: Bilibili
      url: "https://space.bilibili.com/3546693849058014"
    - name: Steam
      url: "https://steamcommunity.com/id/mos9527"

menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: extern
      name: "extern"
      url: /posts/links
